sudo: true

before_cache:
  - rm -f  ~/.gradle/caches/modules-2/modules-2.lock
  - rm -rf ~/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - ~/.npm
    - ~/.nvm
    - ~/.cache/yarn
    - ~/.rustup
    - ~/.cargo
    - ~/android-ndk
    - ~/android-sdk
    - node_modules
    # https://docs.travis-ci.com/user/languages/android/#caching
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/
    - ~/.android/build-cache
    # cache built artifacts
    - app/build/outputs
 
env:
  global:
    # runtime versions
    - RUST_VERSION=1.32.0
    - RUST_TARGETS="aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android"
    - NODE_VERSION=10
    - YARN_VERSION=1.15.2
    - ANDROID_SDK_VERSION=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_NDK_VERSION=r19c
    # misc
    - ANDROID_SDK_CHECKSUM_LINUX=92ffee5a1d98d856634e8b71132e8a95d96c83a63fde1099be3d86df3106def9
    - ANDROID_SDK_CHECKSUM_OSX=ecb29358bc0f13d7c2fa0f9290135a5b608e38434aad9bf7067d0252c160853e
    - ANDROID_NDK_CHECKSUM_LINUX=fd94d0be6017c6acbd193eb95e09cf4b6f61b834
    - ANDROID_NDK_CHECKSUM_OSX=f46b8193109bba8a58e0461c1a48f4534051fb25
    - ANDROID_HOME=${HOME}/android-sdk
    - ANDROID_NDK_HOME=${HOME}/android-ndk/android-ndk-${ANDROID_NDK_VERSION}
    - PATH=$PATH:${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
    - GITHUB_USERNAME=rnd-at-emurgo
    - GITHUB_EMAIL=rnd@emurgo.io
    - GIT_SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
    - CARDANO_NETWORK=mainnet
    - DISPLAY=:0
    # secrets from the ui
    # For rendering google-services.json.tpl:
    # - ANDROID_PROJECT_NUMBER
    # - ANDROID_FIREBASE_URL
    # - ANDROID_PROJECT_ID
    # - ANDROID_STORAGE_BUCKET
    # - ANDROID_MOBILESDK_APP_ID
    # - ANDROID_PACKAGE_NAME
    # - ANDROID_CLIENT_ID
    # - ANDROID_API_KEY
    # For rendering GoogleService-Info.plist.tpl:
    # - IOS_AD_UNIT_ID_FOR_BANNER_TEST
    # - IOS_AD_UNIT_ID_FOR_INTERSTITIAL_TEST
    # - IOS_CLIENT_ID
    # - IOS_REVERSED_CLIENT_ID
    # - IOS_API_KEY
    # - IOS_GCM_SENDER_ID
    # - IOS_PLIST_VERSION
    # - IOS_BUNDLE_ID
    # - IOS_PROJECT_ID
    # - IOS_STORAGE_BUCKET
    # - IOS_GOOGLE_APP_ID
    # - IOS_DATABASE_URL


before_install:
  - bash .travis/before_install.sh

install: 
  - bash .travis/install.sh

stages:
  - build-yoroi
  - deploy-artifacts
#  - build-docker

matrix:
  fast_finish: true
  include:

    - stage: build-yoroi
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
      language: node_js
      node_js: '10'
      name: "build Yoroi app (Android)"
      script: bash .travis/build_yoroi_android.sh

    - stage: build-yoroi
      os: osx
      osx_image: xcode10.2
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 6s Plus
      podfile: ios/Podfile
      name: "build Yoroi app (iOS)"
      before_install: bash .travis/build_yoroi_ios.sh

    #- stage: build-docker
    #  script: false

  allow_failures:
    - stage: build-docker

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      # notify rcmorano
      - secure: uLazaQzraN0KlITJo3LiZ+eNP8UPuoLrtk2m7KWQPaqx2pUlBwAQKh7aSVj+QfnXUa4nQ6Q4HPq2P6j08GhD4b5vGjs7bmPk8ro2mnX/ECfgqfuon1CpvvD856DRJB1NlzI0BTlZlTLZ24TfvYFBB4CF5rh+Fe0DESNqqpwbLwOzQMms21I8VM/oFxOx+d4Uu7/rthIk0juxjS1DPLm+Owk761+MzQRq0XQYpsZpvE2w7ESJzpMjp8qTFKbNwJXbiel0ITNRzhzGVVKTNCNPnnbFSy2Ol6/6aLetLOnMQI1S+VZhUifigvcA9Pov9V6BHYk9+mCrsK93XavTwxSYUNenIf2zmIxkHzz0+EV9DXCysFNyxNq8QqOfwfDLHsfnKd2OsbJ/T5XuciHdizK04Fbp4hUl7HewUn7ywm0p8d+27Ddlrbxy5fdTOu+2YvivOpN5le200Xyhoa8u7fP9AhiRDdPCfor8KCbDRDjmZXTPlJFB8FoSs7bAOUQRuTvZqkI7E0BYrXEbGBwL3WANEb0HFECxg22Nxgx5wV4/owyX+iKN2MXLjKQnSUYCUhbu1xPhztd6jScMoNY0yirKVVbn3z6uuOJs3sk+MM5BrPY1PLtDj8cMqYHAGjsgvSRLFsKkwRQsmulrSyJAVY9z8AVmv3CSf6X9LQVCJKjY8SY=
